//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProveedorSOAP_Client.ProveedorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProveedor", Namespace="http://tempuri.org/", ItemName="proveedor")]
    [System.SerializableAttribute()]
    public class ArrayOfProveedor : System.Collections.Generic.List<ProveedorSOAP_Client.ProveedorServiceReference.proveedor> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="proveedor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProveedorServiceReference.ProveedorWebService1Soap")]
    public interface ProveedorWebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetProveedorResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProveedor", ReplyAction="*")]
        ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorResponse GetProveedor(ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorResponse> GetProveedorAsync(ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProveedor", ReplyAction="*")]
        ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorResponse ObtenerProveedor(ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorResponse> ObtenerProveedorAsync(ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarProveedor", ReplyAction="*")]
        ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorResponse AgregarProveedor(ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorResponse> AgregarProveedorAsync(ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarProveedor", ReplyAction="*")]
        bool BorrarProveedor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> BorrarProveedorAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProveedor", Namespace="http://tempuri.org/", Order=0)]
        public ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequestBody Body;
        
        public GetProveedorRequest() {
        }
        
        public GetProveedorRequest(ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProveedorRequestBody {
        
        public GetProveedorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProveedorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorResponseBody Body;
        
        public GetProveedorResponse() {
        }
        
        public GetProveedorResponse(ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProveedorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProveedorSOAP_Client.ProveedorServiceReference.ArrayOfProveedor GetProveedorResult;
        
        public GetProveedorResponseBody() {
        }
        
        public GetProveedorResponseBody(ProveedorSOAP_Client.ProveedorServiceReference.ArrayOfProveedor GetProveedorResult) {
            this.GetProveedorResult = GetProveedorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProveedor", Namespace="http://tempuri.org/", Order=0)]
        public ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequestBody Body;
        
        public ObtenerProveedorRequest() {
        }
        
        public ObtenerProveedorRequest(ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProveedorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public ObtenerProveedorRequestBody() {
        }
        
        public ObtenerProveedorRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProveedorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorResponseBody Body;
        
        public ObtenerProveedorResponse() {
        }
        
        public ObtenerProveedorResponse(ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProveedorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProveedorSOAP_Client.ProveedorServiceReference.proveedor ObtenerProveedorResult;
        
        public ObtenerProveedorResponseBody() {
        }
        
        public ObtenerProveedorResponseBody(ProveedorSOAP_Client.ProveedorServiceReference.proveedor ObtenerProveedorResult) {
            this.ObtenerProveedorResult = ObtenerProveedorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarProveedor", Namespace="http://tempuri.org/", Order=0)]
        public ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequestBody Body;
        
        public AgregarProveedorRequest() {
        }
        
        public AgregarProveedorRequest(ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarProveedorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email;
        
        public AgregarProveedorRequestBody() {
        }
        
        public AgregarProveedorRequestBody(string Nombre, string Direccion, string Telefono, string Email) {
            this.Nombre = Nombre;
            this.Direccion = Direccion;
            this.Telefono = Telefono;
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarProveedorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorResponseBody Body;
        
        public AgregarProveedorResponse() {
        }
        
        public AgregarProveedorResponse(ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarProveedorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarProveedorResult;
        
        public AgregarProveedorResponseBody() {
        }
        
        public AgregarProveedorResponseBody(bool AgregarProveedorResult) {
            this.AgregarProveedorResult = AgregarProveedorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProveedorWebService1SoapChannel : ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProveedorWebService1SoapClient : System.ServiceModel.ClientBase<ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap>, ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap {
        
        public ProveedorWebService1SoapClient() {
        }
        
        public ProveedorWebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProveedorWebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorWebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorWebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorResponse ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap.GetProveedor(ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequest request) {
            return base.Channel.GetProveedor(request);
        }
        
        public ProveedorSOAP_Client.ProveedorServiceReference.ArrayOfProveedor GetProveedor() {
            ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequest inValue = new ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequest();
            inValue.Body = new ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequestBody();
            ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorResponse retVal = ((ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap)(this)).GetProveedor(inValue);
            return retVal.Body.GetProveedorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorResponse> ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap.GetProveedorAsync(ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequest request) {
            return base.Channel.GetProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorResponse> GetProveedorAsync() {
            ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequest inValue = new ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequest();
            inValue.Body = new ProveedorSOAP_Client.ProveedorServiceReference.GetProveedorRequestBody();
            return ((ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap)(this)).GetProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorResponse ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap.ObtenerProveedor(ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequest request) {
            return base.Channel.ObtenerProveedor(request);
        }
        
        public ProveedorSOAP_Client.ProveedorServiceReference.proveedor ObtenerProveedor(string nombre) {
            ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequest inValue = new ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequest();
            inValue.Body = new ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequestBody();
            inValue.Body.nombre = nombre;
            ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorResponse retVal = ((ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap)(this)).ObtenerProveedor(inValue);
            return retVal.Body.ObtenerProveedorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorResponse> ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap.ObtenerProveedorAsync(ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequest request) {
            return base.Channel.ObtenerProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorResponse> ObtenerProveedorAsync(string nombre) {
            ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequest inValue = new ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequest();
            inValue.Body = new ProveedorSOAP_Client.ProveedorServiceReference.ObtenerProveedorRequestBody();
            inValue.Body.nombre = nombre;
            return ((ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap)(this)).ObtenerProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorResponse ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap.AgregarProveedor(ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequest request) {
            return base.Channel.AgregarProveedor(request);
        }
        
        public bool AgregarProveedor(string Nombre, string Direccion, string Telefono, string Email) {
            ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequest inValue = new ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequest();
            inValue.Body = new ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Direccion = Direccion;
            inValue.Body.Telefono = Telefono;
            inValue.Body.Email = Email;
            ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorResponse retVal = ((ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap)(this)).AgregarProveedor(inValue);
            return retVal.Body.AgregarProveedorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorResponse> ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap.AgregarProveedorAsync(ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequest request) {
            return base.Channel.AgregarProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorResponse> AgregarProveedorAsync(string Nombre, string Direccion, string Telefono, string Email) {
            ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequest inValue = new ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequest();
            inValue.Body = new ProveedorSOAP_Client.ProveedorServiceReference.AgregarProveedorRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Direccion = Direccion;
            inValue.Body.Telefono = Telefono;
            inValue.Body.Email = Email;
            return ((ProveedorSOAP_Client.ProveedorServiceReference.ProveedorWebService1Soap)(this)).AgregarProveedorAsync(inValue);
        }
        
        public bool BorrarProveedor(int id) {
            return base.Channel.BorrarProveedor(id);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarProveedorAsync(int id) {
            return base.Channel.BorrarProveedorAsync(id);
        }
    }
}
